version: "3.5"

services:
  nestjs:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
     - ./api/.env
    ports:
      - 8080:5000
    volumes:
      - ./api/:/app
      - /app/node_modules

  # react_app:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #    - ./frontend/.env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/:/app
  #     - /app/node_modules

  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=musicians
      - POSTGRES_USER=lenny
      - POSTGRES_PASSWORD=lenny
    ports:
     - 5432:5432
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  redis:
    image: redis:6.2-rc1
    environment:
      REDIS_PASSWORD: password

  redis_commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis