export { BecomeMusician } from './become-musician.page';
export { default as EditAccount } from './edit-account.page';
export { EditBand } from './edit-band.page';
export { default as EditProfile } from './edit-profile.page';
export { GoalDonation } from './goals-donations.page';
export { default as Home } from './home.page';
export { default as Login } from './login.page';
export { default as ManageBands } from './bands-manage.page';
export { default as Musician } from './musician.page';
export { NewBand } from './bands-new.page';
export { NewGoal } from './goals-new.page';
export { NewProduct } from './products.new-page';
export { Payment } from './payment.page';
export { Products } from './products.page';
export { default as Register } from './register.page';
export { default as Settings } from './settings.page';
export { default as Transactions } from './transactions.page';
export { default as User } from './user.page';
export { default as GoalsPage } from './goals.page';
export { LikedSongs } from './liked-songs.page';
